# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-14 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('sex', models.IntegerField()),
                ('email', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
